version: "3"
services:
  web:
    build: .
    image: docker_rootpath
    container_name: docker_rootpath
    volumes:
      - ./htdocs:/var/www/html
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 8080:80

